name: rst
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - numpy
  - scipy
  - h5py
  - scikit-learn
  - matplotlib
  - pyyaml
  - tqdm
  - pip
  - pip:
    - timm==1.0.15
    - setigen
    - blimpy